#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/profile.env"
cat <<EOF
ADAPTER_ID=$ADAPTER_ID
PLAN_CAPTURE=$PLAN_CAPTURE
LOCK_OBSERVATION=$LOCK_OBSERVATION
TEMP_SPILL_METRICS=$TEMP_SPILL_METRICS
SHARED_MEMORY_CONTROL=$SHARED_MEMORY_CONTROL
SESSION_MEMORY_CONTROL=$SESSION_MEMORY_CONTROL
PLAN_CAPTURE_FORMAT=$PLAN_CAPTURE_FORMAT
EOF
